run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # enabled by takt
    - errorlint
    - goimports
    - revive
    - gosec
    - exportloopref
    - misspell

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
